title: Pavani Pragada # your name (or website title) here
logo: "/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am currently pursuing my Master's in Business Analytics
  <br><br>
  Also working as Data Analytics Intern at Beechtree Diagnostics.Data-driven strategist adept at turning intricate data into actionable insights.   
  <br><br>
  <a href="htps://linkedin.com/in/pavani-pragada">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

